const present = new Date()

console.log(present)
console.log('getDate:', present.getDate())
console.log('getDay:', present.getDay())
console.log('getFullYear:', present.getFullYear())
console.log('getHours:', present.getHours())
console.log('getMinutes', present.getMinutes())
console.log('getSeconds', present.getSeconds())
console.log('getMilliseconds', present.getMilliseconds())

console.log('timestamp:', present.getTime())
console.log('toLocaleString:', present.toLocaleString())
console.log('toDateString:', present.toDateString())
console.log('toTimeString:', present.toTimeString())